// AUTO-GENERATED by `cargo xtask gen-manifest` - DO NOT EDIT

/** All available languages */
export const availableLanguages: string[] = [
  "css",
  "html",
  "javascript",
  "json",
  "scss",
  "tsx",
  "typescript",
  "xml",
];