; DO NOT EDIT - This file is generated by `cargo xtask gen-crates`
; To modify, edit the source in grammars/tree-sitter-*/queries/
; or add extra_injections in grammars/tree-sitter-*/grammar-crate-config.toml


(raw_text) @none

[
  "as"
  "key"
  "html"
  "snippet"
  "render"
] @keyword

"const" @type.qualifier

[
  "if"
  "else"
  "then"
] @keyword.conditional

"each" @keyword.repeat

[
  "await"
  "then"
] @keyword.coroutine

"catch" @keyword.exception

"debug" @keyword.debug

[
  "{"
  "}"
] @punctuation.bracket

[
  "#"
  ":"
  "/"
  "@"
] @tag.delimiter