// AUTO-GENERATED by `cargo xtask gen-manifest` - DO NOT EDIT

/** Version of plugin packages (all @arborium/* packages share this version) */
export const pluginVersion = "<%= version %>";

/** All available languages */
export const availableLanguages: string[] = [
<% for lang in languages { %>  "<%= lang %>",
<% } %>];
